# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build site

on:
  push:
    branches: [ build-files ]
#   pull_request:
#     branches: [ "*" ]
  workflow_dispatch:

jobs:
  build-page:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0']
        node-version: ['14.x']

    steps:
    - uses: actions/checkout@v2
      with:
        ref: build-files
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      
    - run: npm ci
    
    - run: pwd
  
#     - name: Cache
#       uses: actions/cache@v2.1.7
#       with:
#         # A list of files, directories, and wildcard patterns to cache and restore
#         path: "./*"
#         # An explicit key for restoring and saving the cache
#         key: "npm"
        
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && bundle install && bundle exec jekyll build"
        
    - name: Upload generated artefacts
      uses: actions/upload-artifact@v1
      with:
        name: site_files
        path: _site
        
  push-site:
    runs-on: ubuntu-latest
    needs: build-page
    steps:
    - name: "Checkout pages branch"
      uses: actions/checkout@v2.4.0
      with:
        ref: gh-pages
    - name: "Download artefacts"
      uses: actions/download-artifact@v2.0.10
      with:
        # Artifact name
        name: site_files
    - name: "Push to gh-pages branch"
      run: |
        git config --global user.name '${{ secrets.GIT_NAME }}'
        git config --global user.email '${{ secrets.GIT_EMAIL }}'
        git add .
        git commit -m "Updated page build push"
        git push 
